apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaos-monkey-pod-deployment
  namespace: devops-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chaos-monkey-pod
  template:
    metadata:
      labels:
        app: chaos-monkey-pod
    spec:
      serviceAccountName: chaos-monkey-pod-sa
      containers:
        - name: chaos-monkey-pod
          image: kernelkappa/chaos-monkey-pod:1.2.0
          env:
            - name: TARGET_NAMESPACE
              value: 'testing'
            - name: TARGET_LABEL
              value: 'chaos-monkey%3Dmonkey-victim'
            - name: QUARTZ_CRON_EXPR
              value: '0 0/1 * * * ?'
          resources:
            limits:
              memory: "1G"
              cpu: "1000m"
            requests:
              memory: "512M"
              cpu: "400m"

