---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chaos-monkey-pod-cr
rules:
  - apiGroups: ["*"]
    resources: ["pods"]
    verbs: ["list", "delete"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chaos-monkey-pod-sa
  namespace: devops-tools
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chaos-monkey-pod-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: chaos-monkey-pod-cr
subjects:
- kind: ServiceAccount
  name: chaos-monkey-pod-sa
  namespace: devops-tools


#curl --cacert ca.crt -H "Authorization: Bearer {token}" https://kubernetes.docker.internal:6443/api/v1/pod/namespaces/devops-tools