apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: testing
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 5
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
        chaos-monkey: monkey-victim
    spec:
      containers:
        - name: nginx
          image: nginx
          resources:
            limits:
              memory: "1G"
              cpu: "1000m"
            requests:
              memory: "512M"
              cpu: "400m"
          ports:
          - containerPort: 80
